---
- name: General Kubernetes Setup
  hosts: all
  become: yes
  tasks:
  
    # -------------------------------
    # Step 3: Provision with Ansible
    # -------------------------------

    - name: Placeholder for task 3
      debug:
        msg: "Starting general setup on {{ inventory_hostname }}"

    # -------------------------------
    # Step 4: Register SSH Keys
    # -------------------------------

    - name: Ensure ~/.ssh exists for vagrant user
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: Install all team public SSH keys into authorized_keys
      ansible.builtin.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ lookup('fileglob', './ssh_keys/*.pub', wantlist=True) }}"

    # -------------------------------
    # Step 5: Disable SWAP
    # -------------------------------

    - name: Disable swap immediately
      ansible.builtin.shell: "swapoff -a"
      when: ansible_swaptotal_mb | int > 0

    - name: Remove swap entry from /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^\s*[^#].*\s+swap\s+.*$'
        state: absent

    # -------------------------------
    # Step 6: br_netï¬lter
    # -------------------------------

    - name: Ensure overlay and br_netfilter load on boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load overlay module now
      ansible.builtin.modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter now
      ansible.builtin.modprobe:
        name: br_netfilter
        state: present

    # -------------------------------
    # Step 7: Enable IPv4 forwarding
    # -------------------------------

    - name: Configure required sysctl parameters
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/k8s.conf
        reload: yes
      loop:
        - { key: net.bridge.bridge-nf-call-iptables, value: '1' }
        - { key: net.bridge.bridge-nf-call-ip6tables, value: '1' }
        - { key: net.ipv4.ip_forward, value: '1' }
      tags: [k8s-prereq]


    # -------------------------------
    # Step 8: Manage /etc/hosts
    # -------------------------------

    - name: Generate and copy /etc/hosts file
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
      tags: [network]
    
    # -------------------------------
    # Step 9: Add Kubernetes Repository
    # -------------------------------

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present

    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present
        filename: kubernetes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    # -------------------------------
    # Step 10: Install K8s Tools
    # -------------------------------

    - name: Install containerd and runc
      ansible.builtin.apt:
        name:
          - containerd=1.7.24-*
          - runc=1.1.12-*
        state: present
        allow_downgrade: yes

    - name: Install Kubernetes tools
      ansible.builtin.apt:
        name:
          - kubeadm=1.32.4-*
          - kubelet=1.32.4-*
          - kubectl=1.32.4-*
        state: present
        allow_downgrade: yes

    - name: Hold Kubernetes packages at current version
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubeadm
        - kubelet
        - kubectl
        - containerd
        - runc

    # -------------------------------
    # Step 11: Configure Containerd
    # -------------------------------

    - name: Create containerd config directory
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Disable AppArmor in containerd config
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*disable_apparmor\s*='
        line: '    disable_apparmor = true'
        state: present

    - name: Update sandbox image version
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*sandbox_image\s*='
        line: '    sandbox_image = "registry.k8s.io/pause:3.10"'
        state: present

    - name: Enable SystemdCgroup
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*SystemdCgroup\s*='
        line: '            SystemdCgroup = true'
        state: present

    - name: Restart containerd service
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: yes

    # -------------------------------
    # Step 12: Kubelet
    # -------------------------------

    - name: Enable and start kubelet service
      ansible.builtin.service:
        name: kubelet
        enabled: yes
        state: started